version: 2

sources:
  - name: Financeiro
    description: 'Dados brutos do sistema financeiro da empresa'
    schema: dbt_dw_raw

    tables:
      - name: dados_financeiros
        description: 'Tabela com lancamentos do financeiro da empresa'
        
        columns:
          - name: nome
            description: 'Nome do tipo de lancamento financeiro para cada transacao'
          - name: data
            description: 'Data do lançamento financeiro'
          - name: valor
            description: 'Valor monetário do lançamento financeiro'
          - name: status
            description: 'Status do lançamento (ex: pago, pendente, cancelado)'
          - name: banco
            description: 'Banco utilizado na transação financeira'
          - name: destino
            description: 'Conta ou entidade de destino do valor'
          - name: responsavel
            description: 'Pessoa responsável pelo lançamento ou aprovação'
          - name: tipo
            description: 'Tipo de transação financeira (ex: débito, crédito, transferência)'
          - name: valor_real
            description: 'Valor real após descontos, taxas ou ajustes'
          - name: categoria
            description: 'Categoria do lançamento financeiro (ex: receita, despesa, investimento)'
          - name: mes
            description: 'Mês de referência do lançamento financeiro'