version: 2

sources:
  - name: Financeiro
    description: 'Dados brutos do sistema financeiro da empresa'
    schema: dbt_dw_raw
    loader: bigquery

    tables:
      - name: dados_financeiros
        description: 'Tabela com lancamentos do financeiro da empresa'
        
        columns:
          - name: nome
            description: 'Nome do tipo de lancamento financeiro para cada transacao'
          - name: data
            description: 'Data do lançamento financeiro'
            tests:
              - not_null
          - name: valor
            description: 'Valor monetário do lançamento financeiro'
          - name: status
            description: 'Status do lançamento (ex: pago, pendente, cancelado)'
          - name: banco
            description: 'Banco utilizado na transação financeira'
          - name: destino
            description: 'Conta ou entidade de destino do valor'
          - name: responsavel
            description: 'Pessoa responsável pelo lançamento ou aprovação'
          - name: tipo
            description: 'Tipo de transação financeira (ex: débito, crédito, transferência)'
          - name: valor_real
            description: 'Valor real após descontos, taxas ou ajustes'
          - name: categoria
            description: 'Categoria do lançamento financeiro (ex: receita, despesa, investimento)'
          - name: mes
            description: 'Mês de referência do lançamento financeiro'

      - name: orders
        description: 'Tabelas com informações dos pedidos da Northwind'

        columns:
          - name: order_id
            description: 'Identificador único do pedido'
            tests:
              - not_null
              - unique
          - name: customer_id
            description: 'Identificador do cliente que realizou o pedido'
            tests:
              - not_null
          - name: employee_id
            description: 'Identificador do funcionário responsável pelo pedido'
            tests:
              - not_null
          - name: order_date
            description: 'Data em que o pedido foi realizado'
          - name: required_date
            description: 'Data em que o pedido deve ser entregue ao cliente'
          - name: shipped_date
            description: 'Data em que o pedido foi despachado para o cliente'
          - name: ship_via
            description: 'Identificador do transportador responsável pela entrega'
          - name: freight
            description: 'Valor do frete do pedido'
          - name: ship_name
            description: 'Nome do destinatário da entrega'
          - name: ship_address
            description: 'Endereço de entrega do pedido'
          - name: ship_city
            description: 'Cidade de entrega do pedido'
          - name: ship_region
            description: 'Região de entrega do pedido'
          - name: ship_postal_code
            description: 'Código postal do endereço de entrega'
          - name: ship_country
            description: 'País de entrega do pedido'

      - name: order_details
        description: 'Detalhes dos pedidos da Northwind'

        columns:
          - name: order_id
            description: 'Identificador do pedido ao qual o detalhe pertence'
            tests:
              - not_null
          - name: product_id
            description: 'Identificador do produto no detalhe do pedido'
            tests:
              - not_null
          - name: unit_price
            description: 'Preço unitário do produto no momento do pedido'
          - name: quantity
            description: 'Quantidade de produtos no detalhe do pedido'
          - name: discount
            description: 'Desconto aplicado ao produto no detalhe do pedido'

      - name: categories
        description: 'Categorias de produtos da Northwind'

        columns:
          - name: category_id
            description: 'Identificador único da categoria'
            tests:
              - not_null
              - unique
          - name: category_name
            description: 'Nome da categoria do produto'
            tests:
              - accepted_values:
                  values: ['Beverages', 'Condiments', 'Confections', 'Dairy Products', 'Grains/Cereals', 'Meat/Poultry', 'Produce', 'Seafood']
          - name: description
            description: 'Descrição da categoria do produto'
          - name: picture
            description: 'Imagem associada à categoria do produto'
      
      - name: customers
        description: 'Informações dos clientes da Northwind'

        columns:
          - name: customer_id
            description: 'Identificador único do cliente'
            tests:
              - not_null
              - unique
          - name: company_name
            description: 'Nome da empresa do cliente'
          - name: contact_name
            description: 'Nome do contato principal do cliente'
          - name: contact_title
            description: 'Título do contato principal do cliente'
          - name: address
            description: 'Endereço do cliente'
          - name: city
            description: 'Cidade do cliente'
          - name: region
            description: 'Região do cliente'
          - name: postal_code
            description: 'Código postal do cliente'
          - name: country
            description: 'País do cliente'
          - name: phone
            description: 'Telefone de contato do cliente'
          - name: fax
            description: 'Fax de contato do cliente'
      
      - name: employees
        description: 'Informações dos funcionários da Northwind'

        columns:
          - name: employee_id
            description: 'Identificador único do funcionário'
            tests:
              - not_null
              - unique
          - name: last_name
            description: 'Sobrenome do funcionário'
          - name: first_name
            description: 'Nome do funcionário'
          - name: title
            description: 'Título do cargo do funcionário'
          - name: title_of_courtesy
            description: 'Título de cortesia do funcionário'
          - name: birth_date
            description: 'Data de nascimento do funcionário'
          - name: hire_date
            description: 'Data de contratação do funcionário'
          - name: address
            description: 'Endereço do funcionário'
          - name: city
            description: 'Cidade onde o funcionário reside'
          - name: region
            description: 'Região onde o funcionário reside'
          - name: postal_code
            description: 'Código postal do endereço do funcionário'
          - name: country
            description: 'País onde o funcionário reside'
          - name: home_phone
            description: 'Telefone residencial do funcionário'
          - name: extension
            description: 'Extensão telefônica do funcionário'
          - name: photo
            description: 'Foto do funcionário'
          - name: reports_to
            description: 'Identificador do gerente ao qual o funcionário se reporta'
          - name: photo_path
            description: 'Caminho para a foto do funcionário'
      
      - name: products
        description: 'Informações dos produtos da Northwind'

        columns:
          - name: product_id
            description: 'Identificador único do produto'
            tests:
              - not_null
              - unique
          - name: product_name
            description: 'Nome do produto'
          - name: supplier_id
            description: 'Identificador do fornecedor do produto'
          - name: category_id
            description: 'Identificador da categoria do produto'
          - name: quantity_per_unit
            description: 'Quantidade de produto por unidade'
          - name: unit_price
            description: 'Preço unitário do produto'
          - name: units_in_stock
            description: 'Quantidade de unidades em estoque'
          - name: units_on_order
            description: 'Quantidade de unidades em pedido'
          - name: reorder_level
            description: 'Nível de reabastecimento do produto'
          - name: discontinued
            description: 'Indica se o produto está descontinuado'

      - name: suppliers
        description: 'Informações dos fornecedores da Northwind'

        columns:
          - name: supplier_id
            description: 'Identificador único do fornecedor'
            tests:
              - not_null
              - unique
          - name: company_name
            description: 'Nome da empresa fornecedora'
          - name: contact_name
            description: 'Nome do contato principal do fornecedor'
          - name: contact_title
            description: 'Título do contato principal do fornecedor'
          - name: address
            description: 'Endereço do fornecedor'
          - name: city
            description: 'Cidade do fornecedor'
          - name: region
            description: 'Região do fornecedor'
          - name: postal_code
            description: 'Código postal do fornecedor'
          - name: country
            description: 'País do fornecedor'
          - name: phone
            description: 'Telefone de contato do fornecedor'
          - name: fax
            description: 'Fax de contato do fornecedor'
          - name: home_page
            description: 'Página inicial ou site do fornecedor'
      
      - name: shippers
        description: 'Informações dos transportadores da Northwind'

        columns:
          - name: shipper_id
            description: 'Identificador único do transportador'
            tests:
              - not_null
              - unique
          - name: company_name
            description: 'Nome da empresa de transporte'
          - name: phone
            description: 'Telefone de contato do transportador'

      - name: region
        description: 'Regiões geográficas da Northwind'

        columns:
          - name: region_id
            description: 'Identificador único da região'
            tests:
              - not_null
              - unique
          - name: region_description
            description: 'Descrição da região geográfica'

      - name: territories
        description: 'Territórios geográficos da Northwind'

        columns:
          - name: territory_id
            description: 'Identificador único do território'
            tests:
              - not_null
              - unique
          - name: territory_description
            description: 'Descrição do território geográfico'
          - name: region_id
            description: 'Identificador da região à qual o território pertence'
            tests:
              - not_null
      
      - name: employee_territories
        description: 'Associação entre funcionários e territórios geográficos'

        columns:
          - name: employee_id
            description: 'Identificador do funcionário associado ao território'
            tests:
              - not_null
          - name: territory_id
            description: 'Identificador do território associado ao funcionário'
            tests:
              - not_null
      
      - name: us_states
        description: 'Estados dos Estados Unidos'

        columns:
          - name: state_id
            description: 'Identificador único do estado'
            tests:
              - not_null
              - unique
          - name: state_name
            description: 'Nome do estado'
          - name: state_abbr
            description: 'Abreviação do estado'
          - name: state_region
            description: 'Região geográfica do estado'
      
      - name: country_codes
        description: 'Códigos de países e suas informações'

        columns:
          - name: country_code
            description: 'Código do país'
            tests:
              - not_null
              - unique
          - name: country_name
            description: 'Nome do país'